name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests with coverage
        run: go test -v -coverprofile="coverage.out" ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV }}
